//! Help text content for the help modal

use super::keymap::Keymap;

/// Get keybinding help text for the current keymap
pub fn get_help_text(keymap: Keymap) -> Vec<&'static str> {
    match keymap {
        Keymap::Vim => vec![
            "=== Vim Keybindings ===",
            "",
            "Navigation:",
            "  h/j/k/l      Move left/down/up/right",
            "  Arrow keys   Move cursor",
            "  PageUp/Down  Scroll by page",
            "  Home/End     First/last column",
            "  G            Go to last row with data",
            "  g            Open goto prompt",
            "",
            "Editing:",
            "  i / Enter    Edit cell",
            "  x / Delete   Clear cell",
            "  Esc          Cancel edit",
            "",
            "Selection:",
            "  v            Enter visual mode",
            "  y            Yank (copy)",
            "  p            Paste",
            "",
            "Undo/Redo:",
            "  u            Undo",
            "  Ctrl+r       Redo",
            "",
            "Other:",
            "  :            Enter command mode",
            "  Ctrl+s       Save",
            "  Ctrl+q       Quit",
            "  P            Open plot modal",
            "  +/-          Adjust column width",
        ],
        Keymap::Emacs => vec![
            "=== Emacs Keybindings ===",
            "",
            "Navigation:",
            "  C-n/C-p      Move down/up",
            "  C-f/C-b      Move right/left",
            "  Arrow keys   Move cursor",
            "  C-v/M-v      Page down/up",
            "  C-a/C-e      First/last column",
            "  M->          Go to last row",
            "  M-g          Open goto prompt",
            "",
            "Editing:",
            "  Enter        Edit cell",
            "  C-d/Delete   Clear cell",
            "  C-g / Esc    Cancel",
            "",
            "Selection:",
            "  C-SPC        Set mark (visual)",
            "  M-w          Copy (yank)",
            "  C-y          Paste",
            "",
            "Other:",
            "  M-x          Enter command mode",
            "  C-s          Save",
            "  C-q          Quit",
            "  M-p          Open plot modal",
        ],
    }
}

/// Get command help text
pub fn get_commands_help() -> Vec<&'static str> {
    vec![
        "=== Commands ===",
        "",
        "File:",
        "  :w [file]       Save",
        "  :q              Quit",
        "  :q!             Force quit",
        "  :wq             Save and quit",
        "  :e <file>       Open file",
        "",
        "Import/Export:",
        "  :import <csv>   Import CSV",
        "  :export <csv>   Export CSV",
        "",
        "Row/Column:",
        "  :ir             Insert row above",
        "  :dr             Delete current row",
        "  :ic             Insert column left",
        "  :dc             Delete current column",
        "",
        "Navigation:",
        "  :goto <cell>    Go to cell (e.g. :goto A100)",
        "",
        "Display:",
        "  :colwidth <n>   Set column width",
        "  :cw <col> <n>   Set specific column",
        "",
        "Functions:",
        "  :source <file>  Load Rhai functions",
        "  :so             Reload functions",
        "",
        "Press Esc or q to close",
    ]
}
